server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://localhost:3306/MicroServices
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver    